Меня сaмого немного выворачивает от этого кода. Но лучше пока не прид…
Maksonchik88/Kirienko_lessons_lists pull request #11
Opened 2022-12-19 20:08 UTC by Maksonchik88

…умалось..

2022-12-19 20:12 UTC, Maksonchik88 commented
https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111343#1

2022-12-19 20:19 UTC, Maksonchik88 commented
Вижу уже, что не работает....

2022-12-19 20:33 UTC, iliadmitriev requested changes
Данное решение принять не могу по причине:
1. Не соблюдены договоренности по наименованию файлов
2. В случае если в другом классе попадется однофамилец с тем же именем то это сломает алгоритм
3. Для поиска максимума применена сортировка `sorted` которая менее эффективна, чем обычная линейная функция `max`
В остальном код рабочий

2022-12-19 20:35 UTC, iliadmitriev commented
### Есть предложение.
А что если сделать структуру.

Словарь в котором в качестве ключа будет использована оценка, 
а в качестве значения список строк Фамилия + Имя 

Вот для таких данных:
```
Иванов Сергей 9 93
Сергеев Петр 10 91
Петров Василий 11 92
Васильев Иван 9 93
```

Эта структура будет выглядеть вот так
```python
data = {
    91: ['Сергеев Петр'],
    92: ['Петров Василий'],
    93: ['Иванов Сергей', 'Васильев Иван']
}
```
Мы подобные структуры уже строили

далее можно найти максимальное значение среди ключей `data.keys()`
это будет 93
а так же значение на втором месте 92 (подобный алгоритм мы разбирали когда находили человека на 2-м месте)

После чего просто вытащить из словаря значение по этому ключу (Это будет список фамилий)
Если фамилия одна (длина списка == 1) - то выводим ее, если нет, то выводим длину списка

2022-12-19 20:39 UTC, Maksonchik88 commented
Хорошо)

2022-12-23 10:35 UTC, iliadmitriev requested changes
уже гораздо лучше, но надо доделать

2022-12-23 10:35 UTC, iliadmitriev commented on files/name_of_best_non_winner.py
> +c = [d.keys()].count(pre_max)
переменная `с` будет всегда == 1 потому что ты ищешь количество вхождений ключа (второго по величине),  которые точно есть в словаре среди ключей.
можно просто написать `c = 1` смысл будет тот же
и зачем эта переменная, если ты ее дальше нигде не используешь?

2022-12-23 10:35 UTC, iliadmitriev commented on files/name_of_best_non_winner.py
> +            print(len(v))
зачем перебирать весь словарь, ради того чтобы вытащить одно значение по равенству ключа `k == pre_max`, если у тебя уже есть ключ и ты можешь его просто вытащить обратившись к словарю.

2022-12-23 11:52 UTC, Maksonchik88 commented on files/name_of_best_non_winner.py
> +c = [d.keys()].count(pre_max)
вообще бесполезная

2022-12-23 11:52 UTC, Maksonchik88 commented on files/name_of_best_non_winner.py
> +            print(len(v))
согласен

2022-12-23 11:58 UTC, iliadmitriev approved these changes

2022-12-23 11:58 UTC, iliadmitriev commented on files/name_of_best_non_winner.py
> +print(d)
этот вывод я так понял служил для целей отладки, и для работы программы он не нужен.
такое надо убирать.

2022-12-23 13:31 UTC, merged

2022-12-23 13:32 UTC, Maksonchik88 commented on files/name_of_best_non_winner.py
> +print(d)
учту!