1_st
Maksonchik88/Kirienko_lessons_lists pull request #12
Opened 2022-12-22 08:37 UTC by Maksonchik88

2022-12-22 08:38 UTC, Maksonchik88 commented
закомментировал первое решение. Там я уперся в то, что не понял, как вывести, согласно условию результат. Прошу помочь с этим.

2022-12-23 10:37 UTC, iliadmitriev commented
а есть ссылка на задачу?

2022-12-23 10:40 UTC, iliadmitriev requested changes

2022-12-23 10:40 UTC, iliadmitriev commented on files/school_with_participans.py
> +filtr_max_mem = list(filter(lambda x: x[1][0] == max_mem, d.items()))
лучше избегать решений которые не понимаешь как работают

2022-12-23 11:57 UTC, Maksonchik88 commented on files/school_with_participans.py
> +filtr_max_mem = list(filter(lambda x: x[1][0] == max_mem, d.items()))
https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111344#1

2022-12-24 06:35 UTC, merged