alphabet1
Maksonchik88/Kirienko_lessons_lists pull request #14
Opened 2022-12-23 09:30 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111346#1

1. Файл в программе открывается только, когда использую полный путь файла(
2. Программа написана, исходя из условия (гарантируется, что все фамилии разные)

2022-12-23 11:00 UTC, iliadmitriev requested changes

2022-12-23 11:00 UTC, iliadmitriev commented on files/sort_participants_alphabetically.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
надо правильно настроить рабочую директорию из которой запускаешь программу.
настройки рабочей директории доступны в конфигурации запуска скрипта в pycharm
![Run confiruge](https://resources.jetbrains.com/help/img/idea/2022.3/py_add_new_configuration.png)

2022-12-23 11:00 UTC, iliadmitriev commented on files/sort_participants_alphabetically.py
> +        if el == k:
зачем этот цикл, если просто можно вытаскивать значения из словаря по ключу?

2022-12-23 13:12 UTC, Maksonchik88 commented on files/sort_participants_alphabetically.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
/home/max/projects/kirienko/files - такая сейчас. Не понимаю, как нужно? какой путь?

2022-12-23 13:19 UTC, iliadmitriev commented on files/sort_participants_alphabetically.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
Путь можешь указать в pycharm любой. Но вот путь файла в коде Python должен быть относительный

2022-12-23 13:22 UTC, Maksonchik88 commented on files/sort_participants_alphabetically.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
нужен созвон) после 20.00 можешь?

2022-12-23 13:26 UTC, iliadmitriev commented on files/sort_participants_alphabetically.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
Вот это рабочая директория.

/home/max/projects/kirienko/files

Если относительный путь указывать от нее, то будет просто:
check.txt

Если такая рабочая директория

/home/max/projects/kirienko

То путь относительно нее будет:

files/check.txt

2022-12-24 07:06 UTC, iliadmitriev approved these changes
принято, с одним не критичным замечанием

2022-12-24 07:06 UTC, iliadmitriev commented on files/sort_participants_alphabetically.py
> +    a, b, c, e = line.split()
нет необходимости создавать переменную если ты ее не используешь
тут переменная `c` создается, но не используется нигде в коде далее.
она используется для того чтобы распаковывать список возвращаемый методом `.split()`, состоящий из 4-х элементов (чтобы избежать ошибки)
вместо переменной можно использовать `_`
```python
a, b, _, e = line.split()
```

2022-12-24 08:06 UTC, merged