points1
Maksonchik88/Kirienko_lessons_lists pull request #15
Opened 2022-12-23 10:12 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111347#1

1. Так же проблема с адресом файла ( завтра утром созвонимся, объяснишь мне, что не так и я новые коммиты по всем задачам сделаю).

2022-12-23 12:07 UTC, iliadmitriev requested changes

2022-12-23 12:07 UTC, iliadmitriev commented on files/sort_by_points.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
нужно настроить pycharm чтобы он понимал относительный путь от корня проекта

2022-12-23 12:07 UTC, iliadmitriev commented on files/sort_by_points.py
> +                print()
зачем такая комбинация?
сначала выводить без переноса строки, а потом отдельно печатать перенос строки?

2022-12-23 12:07 UTC, iliadmitriev commented on files/sort_by_points.py
> +                print()
зачем такая комбинация?
сначала выводить без переноса строки, а потом отдельно печатать перенос строки?

2022-12-23 20:19 UTC, Maksonchik88 commented on files/sort_by_points.py
> +                print()
+

2022-12-24 07:22 UTC, iliadmitriev requested changes
есть 2 критиных замечания.

1. лишний(не нужный) перебор элементов повышает вычислительную сложность алгоритма
2. ошибка в реализации, у тебя может быть случай что 3 или больше человек наберут одинаковый балл, но он выведет всего 2-х человек

2022-12-24 07:22 UTC, iliadmitriev commented on files/sort_by_points.py
> +    a, b, c, e = line.split()
не критичное замечание, номер школы который распаковывается и потом не используется

2022-12-24 07:22 UTC, iliadmitriev commented on files/sort_by_points.py
> +        if el == k:
критичное замечание
не надо перебирать все элементы в цикле for, чтобы найти единственный который совпадает,
это усложняет и теряется смысл использования словаря.
смысл словаря в том что всегда можно вытащить нужное значение по известному ключу.
у тебя `el` это ключ (потому что ты сортировал ключи словаря `d` в список `x`)

2022-12-24 07:22 UTC, iliadmitriev commented on files/sort_by_points.py
> +                print(v[1], k)
а если будет 3 элемента в списке `v` (3 человека наберут столько баллов)
то тут нужно еще `print(v[2], k)` (и т. д.)
так что надо переделать/доделать

2022-12-25 06:41 UTC, Maksonchik88 commented on files/sort_by_points.py
> +                print(v[1], k)
Исправил

2022-12-25 08:22 UTC, iliadmitriev requested changes

2022-12-25 08:22 UTC, iliadmitriev commented on files/sort_by_points.py
> +            print(q, el)
в чем смысл этого `if ... else`
если массив содержит 1 элемент печатаем его в строку
если массив содержит больше 1 элемента то печатаем их в строку.

не проще ли просто вывести все элементы списка, построчно?

2022-12-25 08:33 UTC, Maksonchik88 commented on files/sort_by_points.py
> +            print(q, el)
блин))))
я олень)

2022-12-25 09:16 UTC, iliadmitriev approved these changes
другое дело, читать приятно

2022-12-25 09:16 UTC, iliadmitriev commented on files/sort_by_points.py
> +        print(surname, score)
тут не просто фамилия (surname), а полное имя фамилия и имя (fullname)

2022-12-25 09:18 UTC, merged

2022-12-25 09:19 UTC, Maksonchik88 commented on files/sort_by_points.py
> +        print(surname, score)
точно