winners1
Maksonchik88/Kirienko_lessons_lists pull request #16
Opened 2022-12-23 11:33 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111348#1

2022-12-23 12:13 UTC, iliadmitriev requested changes
в целом задача решена правильно. молодец!
но есть мелкие замечания.
надо добить.

2022-12-23 12:13 UTC, iliadmitriev commented on files/schools_whis_winners.py
> +print(max_key)
отладочные принты надо убирать.

2022-12-23 12:13 UTC, iliadmitriev commented on files/schools_whis_winners.py
> +file = open("/home/max/projects/kirienko/files/check.txt")
тут надо настроить pycharm
см https://github.com/Maksonchik88/Kirienko_lessons_lists/pull/14#discussion_r1056247246

2022-12-24 06:46 UTC, Maksonchik88 commented on files/schools_whis_winners.py
> +print(max_key)
убрал

2022-12-24 07:24 UTC, iliadmitriev approved these changes
отличная работа

2022-12-24 07:24 UTC, iliadmitriev commented on files/schools_whis_winners.py
> +max_key = max(dict_1)
не критичное замечание, но желательно привыкать писать код более явным и понятным.
лучше всего указывать что ты ищешь максимум среди ключей
```python
max_key = max(dict_1.keys())
```

2022-12-24 08:07 UTC, merged