sort_by_num_1
Maksonchik88/Kirienko_lessons_lists pull request #18
Opened 2022-12-24 10:31 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111351#1
мне не нравится код

2022-12-24 10:43 UTC, iliadmitriev requested changes
тут смысл задачи был в другом, первые 2 пункта ты выполнил правильно
1. отфильтровать все школы в которых не было участников (это можно не делать, у тебя просто нет таких)
2. аггрегировать - посчитать для каждой школы количество участников и положить данные в словарь.
поскольку мы дожны сортировать по количеству участников, то полученный словарь нам в таком виде не подходит, его надо преобразовать в нужный нам (чтобы ключем было поле по которому сортировать надо)

2023-01-02 06:06 UTC, iliadmitriev requested changes

2023-01-02 06:06 UTC, iliadmitriev commented on files/schools_sort_by_num.py
> +data_revers = sorted(data.items(), key=lambda x: x[1], reverse=True)
Как фильтровать я, к стати, не показывал. Забыл. Надо будет исправить внеси в список вопросов.

А вот как пользоваться лямбдой, я показывал. Для того чтобы это делать эффективно надо понимать что за тип данных `x` и что за тип данных твоя формула возвращает.

В данном примере у тебя, поскольку формула применяется к списку кортежей возвращаемых `data.items()`, это будет кортеж из двух элементов ключ и значение.

Вот тебе пару примеров:

1. Тривиальная лямбда (что на выход, то и на выход)
`lambda x: x`

2. Лямбда которая берет из кортежа  1-й (от 0) элемент
`lambda x: x[1]`
В данном случае у тебя формула будет возвращать уже тип данных int

3. Лямбда которая переставляет элементы кортежа (0, 1) -> (1, 0)
`lambda x: (x[1], x[0])`
Ты как бы берёшь элементы и создаешь из них новый кортеж, переставив элементы

4. Можно инвертировать значение (сделать отрицательным)
`lambda x: (-x[1], x[0])`

Область применения лямбды на этом не ограничивается. Можно использовать для того чтобы преобразовать тип данных, посчитать какое то выражение, подставить значение из словаря.

2023-01-02 09:03 UTC, iliadmitriev requested changes
задача решена правильно, но надо убрать отладочный код

2023-01-02 09:03 UTC, iliadmitriev commented on files/schools_sort_by_num.py
> +print(data_revers)
все решенно правильно, но вот отладочные принты все портят =)

2023-01-02 09:11 UTC, Maksonchik88 commented on files/schools_sort_by_num.py
> +print(data_revers)
блин((

2023-01-02 09:15 UTC, iliadmitriev approved these changes
молодец

2023-01-02 09:18 UTC, merged