commit_1
Maksonchik88/Kirienko_lessons_lists pull request #20
Opened 2022-12-26 19:25 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111353#1

2022-12-26 20:30 UTC, iliadmitriev requested changes
Глобальный максимум (балл победителя посчитан не верно)

2022-12-26 20:30 UTC, iliadmitriev commented on files/schools_with_the_most_winners.py
> +max_score = max(list(map(lambda x: x[0], scores_list)))
Не совсем понятно зачем ты это делаешь. Что делает эта конструкция? Ищет максимум среди первых элементов списка.

Если это для того, чтобы посчитать глобально по всем школам балл победителя, то это надо по всем спискам в словаре, искать максимум, а потом среди полученного списка максимумов искать общий максимум.

Можно без этого обойтись. Есть решение лучше искать этот максимум в самом первом цикле, где ты считываешь файл.

2022-12-27 04:00 UTC, iliadmitriev requested changes
Опиши почему используешь метод get у словаря и как работает параметр key?

2022-12-27 04:00 UTC, iliadmitriev commented on files/schools_with_the_most_winners.py
> +    data_count_of_winners[school] = int(counter)
Не критично, но у тебя counter и так int.

2022-12-27 04:00 UTC, iliadmitriev commented on files/schools_with_the_most_winners.py
> +max_school = (max(data_count_of_winners, key=data_count_of_winners.get))
А как работает функция `max` с параметром `key`? Почему в ней указал метод `.get`?

2022-12-29 08:53 UTC, Maksonchik88 commented on files/schools_with_the_most_winners.py
> +max_school = (max(data_count_of_winners, key=data_count_of_winners.get))
Решил по другому

2022-12-29 10:05 UTC, iliadmitriev approved these changes
отличное решение!

2022-12-29 11:40 UTC, merged