commit_1
Maksonchik88/Kirienko_lessons_lists pull request #21
Opened 2022-12-26 20:46 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111354#1

2022-12-27 04:43 UTC, iliadmitriev requested changes
Решено не верно.
Поправь заголовок pull request'а чтобы было понятно.

2022-12-27 04:43 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +total = sum(list(parties_and_votes.values()))
тут не надо list, потому что `sum` на вход может принимать не только список но и генератор

2022-12-27 04:43 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +parties_and_votes = dict(zip(parties_list, count_voces_list))
Решено не верно.
1. Если во входном файле будет 4 партии? Или партия поменяет название?
2. Ты используешь функцию zip для того чтобы склеить названия партий с количеством голосов, но ведь они могу быть расположены в совершенно произвольном порядке.

2022-12-27 04:43 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
идея хорошая.
а как работает filter? и почему в параметрах `None`?

2022-12-29 09:58 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
Идея заключается в том, что, применяя filter(), мы не указываем параметр function. Таким образом мы фильтруем весь текст файла, применяя строчный метод rstrip() и фильтруем каждую строку, сохраняя ее последовательно в список

2022-12-29 10:00 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
а filter() на деле возвращает True-значения последовательности. В нашей задаче это все строки с применением метода rstrip().

2022-12-29 10:01 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
Разобрался)))

2022-12-29 10:02 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
что значит True-значения? он что ли возвращает boolean? у нас же вроде как строки?

2022-12-29 10:55 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
мы в функцию ничего не инициализировали, поэтому там None. при этом мы итерировали каждый элемент последовательности

2022-12-29 10:57 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
нет, он не возвращает булевое значение, конечно (хотя, может очевидно)). в нашем случае на filter() всё True, поэтому все без исключения элементы последоватльности будут поочередно проитеррированы

2022-12-29 11:07 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
тоесть, он не нужен получается ?

2022-12-29 11:21 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
ну конечно можно обычным циклом так сделать. По сути, метод можно не использовать. Но выглядит красиво.

2022-12-29 13:12 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +lines = list(filter(None, (line.rstrip() for line in lines)))
> все без исключения элементы последоватльности будут поочередно проитеррированы

Если ты используешь все элементы последовательности и ничего не фильтруешь, то зачем в принципе фильтровать ? Зачем эта строчка в коде, даже если она "выглядит красиво"?

2022-12-29 13:17 UTC, iliadmitriev requested changes

2022-12-29 13:17 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +    data_parties_keys[voice] += 1
Вот это сделал правильно и оно будет работать. 
Но не учел один кейс: 
Что если в списке голосов появится голос за несуществующую партию (испорченный билютень так сказать)
То у тебя автоматом этот голос добавится в качестве ключа к партиям и еще этот голос учтется в глобальных голосах

2022-12-29 15:45 UTC, iliadmitriev approved these changes
Принято с мелким замечанием.

2022-12-29 15:45 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +        continue
А это зачем?

2022-12-29 15:47 UTC, Maksonchik88 commented on files/seven_percent_barrie.py
> +        continue
Хз_))

2022-12-29 15:47 UTC, merged

2022-12-29 15:49 UTC, iliadmitriev commented on files/seven_percent_barrie.py
> +        continue
На работу кода это не влияет, но такое лучше не оставлять