Выборы Президента
Maksonchik88/Kirienko_lessons_lists pull request #25
Opened 2022-12-29 19:43 UTC by Maksonchik88

* Открыл файл -> прочитал -> закрыл
* Инициализировал словарь,инициализировал переменную, подсчитывающую общее количество голосов
* Циклом заполнил словарь, где ключом является фамилия кандидата, значением - количество голосов
* Инициализировал четыре переменные: максимальный и предмаксимальный голоса и соотвествующие им имена кандидатов -> циклом по словарю вычислил значения этих переменных
* Проверил, больше ли 50-ти процентов количество максимальных голосов: если да, то вывожу кратную цифре Фамилию Имя если нет, то вывожу кандидатов, кратных сначала максимальнойб затем предмаксимальной переменной с голосами

2022-12-29 19:56 UTC, iliadmitriev requested changes
Есть предложенное улучшение.
И есть ошибка в алгоритме поиска кандидата на 2-е место

2022-12-29 19:56 UTC, iliadmitriev commented on files/presedent_elections.py
> +        data[candidat] += 1
Тут ты увеличиваешь на 1, если в словаре есть ключ и если в словаре нет ключа. А нельзя просто без всяких условий увеличивать ?

2022-12-29 19:56 UTC, iliadmitriev commented on files/presedent_elections.py
> +        max_cand = fullmane
Если я правильно понял, то эта конструкция необходима для поиска победителя и того кто занял 2-е место.
Но есть вариант, что оно может не сработать, если при переборе словаря, сначала встретит кандидата победителя, а потом того  кто занял второе место, то условие не выполнится (потому что количество голосов кандидата на втором месте не может быть больше 1-го) и в итоге кандидат на второе место не будет найден.

2022-12-29 20:09 UTC, Maksonchik88 commented on files/presedent_elections.py
> +        data[candidat] += 1
ну да

2022-12-30 05:50 UTC, iliadmitriev requested changes

2022-12-30 05:50 UTC, iliadmitriev commented on files/presedent_elections.py
> +data_tuple = sorted(data.items(), key=lambda x: x[1], reverse=True)
Сортировка имеет сложность O(n*log(n)).

Перебор имеет линейную сложность O(n)

По этому лучше оставить обычный перебор и сравнение.

Тем более нужно будет объяснить как работает key и lambda.

2022-12-30 10:18 UTC, iliadmitriev requested changes

2022-12-30 10:18 UTC, iliadmitriev commented on files/presedent_elections.py
> +data_tuple = list(data_rev.items())  # [('Варфоломей Виссарионов', 3), ('Полуэкт Варфоломеев', 2), ('Виссарион Полуэктов', 1)]
В словаре не надо перебирать значения во вложенном цикле. Это автоматически делает вычислительную сложность алгоритма квадратичной O(n^2).

Мы это уже делали, когда в создается еще один словарь (обратный) в котором ключом является значение из исходного словаря, а значениями является список ключей. Это делается для последующей сортировки. Тут можно применить похожий подход.

2022-12-30 16:52 UTC, iliadmitriev approved these changes

2022-12-30 18:29 UTC, merged