Выборы Государственной Думы
Maksonchik88/Kirienko_lessons_lists pull request #26
Opened 2022-12-30 09:18 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111357#1 

*Открыл файл -> Прочитал файл целиком  - > Закрыл файл (закрою))) 
*Инициализировал словарь и заполнил его ключами (названия партий) и значениями (количеством голосов) *Инициализировал переменную общей суммы всех голосов 
*Инициализировал и посчитал "первое избирательное частное" 
*Инициализировал и заполнил словарь, в котором ключами являются названия партий, а значениями - списки, состоящие из количества мест в Думу,
 дробной части частного от деления числа голосов за данную партию на первое избирательное частное
*Возникла проблема с дальнейшим присвоением дополнительного балла партии, согласно условию задачи

2022-12-30 09:35 UTC, iliadmitriev requested changes

2022-12-30 09:35 UTC, iliadmitriev commented on files/state_duma_selection.py
> +    number_of_seats[party].append(remainder)
1. Для вычисления целой части дробного числа можно использовать int()
2. Дробную часть можно сравнить с 0.5, если больше то к целой части прибавив +1, можно получить округление
3. Не обязательно хранить отдельно целую и дробную часть.

2023-01-04 09:13 UTC, iliadmitriev approved these changes
Хорошее решение. Красава. Принято.

P.S. Еще можно цикл раньше прерывать как только extra_scores станет равным 0

2023-01-04 14:38 UTC, Maksonchik88 commented
Я это продумал в голове, но не стал исправлять))

2023-01-04 14:38 UTC, merged