Проходной балл
Maksonchik88/Kirienko_lessons_lists pull request #28
Opened 2023-01-01 14:50 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=5763&chapterid=111358#1

*Открыл файл
*Инициализировал переменную из первой строки файла, в к-й хранится кол-во мест *Прочитал все остальные строки файла -> закрыл файл *Инициализировал два словаря и сортировкой заполнил словари, соблюдая условие, что если хоть один предмет сдан менее, чем на 40 баллов,
    то это в словарь непроходных абитуриентов, а если больше -словарь проходных. Ключами в словарях являются средние баллы,
    а значениями - списки абитуриентов
*Отсортировал словари по нисходящей по ключу
*Инициализировал и вычислил через цикл максимальную длину значений в проходном словаре *Проверил, не меньше ли общее число абитуриентов, прошедших первый этап числа месте. Если нет, то дальше *Циклом вычислил проходной бал, вывел его

2023-01-01 14:58 UTC, iliadmitriev requested changes
хорошо, но есть критичные замечания

2023-01-01 14:58 UTC, iliadmitriev commented on files/passing_score.py
> +scores_of_all_university_applicants_sort = dict(sorted(scores_of_all_university_applicants.items(), reverse=True))
ты сортируешь, а потом опять преобразуешь в словарь, по идее теряешь сортировку.
словарь - это не отсортированная структура.

2023-01-01 14:58 UTC, iliadmitriev commented on files/passing_score.py
> +did_not_pass_the_competition_sort = dict(sorted(did_not_pass_the_competition.items(), reverse=True))
тоже самое, словарь - структура не упорядоченная

2023-01-01 14:58 UTC, iliadmitriev commented on files/passing_score.py
> +print(total_did_not_applicants, total_applicants)
отладочный вывод надо убирать

2023-01-01 14:58 UTC, iliadmitriev commented on files/passing_score.py
> +for ball, fulnames in scores_of_all_university_applicants_sort.items():
здесь надо перебирать не словарь, а отстортированый список кортежей

2023-01-01 14:58 UTC, iliadmitriev commented on files/passing_score.py
> +for ball, fulnames in scores_of_all_university_applicants_sort.items():
надо перебирать не словарь, а отсортированный список кортежей

2023-01-01 15:34 UTC, Maksonchik88 commented on files/passing_score.py
> +scores_of_all_university_applicants_sort = dict(sorted(scores_of_all_university_applicants.items(), reverse=True))
Почему так?

2023-01-01 15:37 UTC, iliadmitriev commented on files/passing_score.py
> +scores_of_all_university_applicants_sort = dict(sorted(scores_of_all_university_applicants.items(), reverse=True))
словарь считается не отсортированной структурой, если ты отсортировал а потом опять переделал, в словарь - то считай что не сортировал.

2023-01-01 16:33 UTC, iliadmitriev requested changes

2023-01-01 16:33 UTC, iliadmitriev commented on files/passing_score.py
> +for elem in scores_of_all_university_applicants_sort:
Верни балл и ФИО.
Мы договорились не использовать переменных не значащих.
Если что это у тебя структура самок кортежей - по идее должно работать.

2023-01-01 16:33 UTC, iliadmitriev commented on files/passing_score.py
> +for elem in scores_of_all_university_applicants_sort:
Верни балл и ФИО.

2023-01-01 16:33 UTC, iliadmitriev commented on files/passing_score.py
> +print(did_not_pass_the_competition_sort)
Отладочный принт

2023-01-01 17:35 UTC, iliadmitriev requested changes
проверь отступы, у тебя почему то получилось 8 пробелов при отступе, хотя должно быть 4

2023-01-01 17:35 UTC, iliadmitriev commented on files/passing_score.py
> +                scores_of_all_university_applicants[sum_balls].append(fullname)
у блока внутри for лишний отступ

2023-01-01 17:35 UTC, iliadmitriev commented on files/passing_score.py
> +                did_not_pass_the_competition[sum(balls)].append(fullname)
лишний отступ

2023-01-02 06:21 UTC, iliadmitriev approved these changes
Отлично.

2023-01-02 07:28 UTC, merged