Поезда
Maksonchik88/Kirienko_lessons_lists pull request #30
Opened 2023-01-04 14:43 UTC by Maksonchik88

*нигде не учел константу станций, а так же неверно распределил кол-во …человек по станциям...

2023-01-04 16:38 UTC, iliadmitriev requested changes

2023-01-04 16:38 UTC, iliadmitriev commented on files/trains.py
> +    data[passenger].append(stations)
Ты хранишь в словарике структуру `ФИО пассажира` -> `входная станция, выходная станция`.
А по сути тебе надо посчитать на каком перегоне было максимум пассажиров. Тебе для этой задачи не нужна информация ФИО, и тем более в качестве ключа. Тебе бы лучше хранить станцию и сколько входило и сколько выходило.

2023-01-04 16:38 UTC, iliadmitriev commented on files/trains.py
> +            dict_of_means['4 - 5'] += 1
А что если количество перегонов будет > 5
Тут лучше считать не по перегонам а по станциям (сколько сейчас в вагоне например)

2023-01-05 09:30 UTC, Maksonchik88 commented on files/trains.py
> +            dict_of_means['4 - 5'] += 1
Это я уже усвоил. Этот код неактуальный

2023-01-05 09:32 UTC, iliadmitriev requested changes
Мои общие рекомендации по решению задачи:
1. Перебирать станции начиная с 1 и не доезжать до последней (вести учет по станции отправления)
2. Проверять на каждой станции если пассажиры заходят то их прибавлять к текущему значению пассажиров
3. Так же проверять на каждой станции если на ней пассажиры выходят - вычитать их из текущего количества пассажиров в вагоне.
4. Записывать текущее значение пассажиров в поезде для станции отправления в словарик
5. Так же искать максимальное количество пассажиров в поезде.

2023-01-05 09:32 UTC, iliadmitriev commented on files/trains.py
> +    i += 1
Вот так нельзя делать. 
Чтобы начать цикл с 1, и шагать через 1, нужно просто указать range(1, N, 2)
От 1 и шаг 2.
Плохо когда меняешь переменную цикла в цикле.


Не понятно зачем ты делаешь шаг 2. Для решения задачи как раз не надо перескакивать через одну станцию.

Рекомендую перебирать станции отправления и вести учет по станциям отправления. (Потому что до последней стации из предпоследней пассажиры в любом случае доедут, по условию задачи)

2023-01-05 09:32 UTC, iliadmitriev commented on files/trains.py
> +            pass
Зачем это если ничего не делаешь?

2023-01-05 09:42 UTC, Maksonchik88 commented on files/trains.py
> +            pass
это я не знаю, как дальше))) поэтому pass

2023-01-05 09:51 UTC, iliadmitriev commented on files/trains.py
> +            pass
А мысль какая ? По этому и не знаешь что это что то не нужное.

2023-01-05 11:38 UTC, iliadmitriev requested changes
Все лишнее вычисти

2023-01-05 11:38 UTC, iliadmitriev commented on files/trains.py
> +        data[i] = current_passengers
Нельзя в словарик с текущим кол-вом пассажиров записывать здесь, потому что по факту это не текущее количество пассажиров. Потому что ты к текущим пассажирам только что прибавил тех кто на этой остановке вошли. А что бы реальное количество получить тебе еще надо вычесть тех кто выходит.

2023-01-05 11:38 UTC, iliadmitriev commented on files/trains.py
> +            max_passengers = current_passengers
Нельзя искать максимум в этой точке. Потому что у тебя в этой точке по факту current_passangers это еще не фактическое количество пассажиров в вагоне. Ты прибавил тех кто зашли и не вычел количество вышедших.

2023-01-05 11:38 UTC, iliadmitriev commented on files/trains.py
> +        data[i] = current_passengers
Это по факту не будет работать. Потому что ты ранее посчитал максимум из которого не было вычтено количество вышедших. А это значит что он будет всегда больше.

2023-01-05 11:52 UTC, Maksonchik88 commented on files/trains.py
> +            max_passengers = current_passengers
+

2023-01-05 12:06 UTC, iliadmitriev approved these changes
Решено отлично.

2023-01-05 12:06 UTC, iliadmitriev commented on files/trains.py
> +    _, _, start, end = line.split()
Тут может оказаться что у пассажира ФИО из 3 строк состоит. Тогда это может сломаться. Лучше брать последние 2 элемента.

2023-01-05 12:06 UTC, iliadmitriev commented on files/trains.py
> +    data[i] = current_passengers
Название переменной i без смысла, тут в этой переменой по сути станция station

2023-01-05 19:52 UTC, merged