Номер появления слова
Maksonchik88/Kirienko_lessons_lists pull request #31
Opened 2023-01-06 06:15 UTC by Maksonchik88

*Инициализировал словарь
*Открыл и прочитал файл
*Заполнил словарь слово -> количесво повторений, распечатывая при этом каждое значение в итерации

2023-01-06 09:09 UTC, iliadmitriev commented
А ссылку на задачу добавь?

2023-01-07 14:17 UTC, iliadmitriev requested changes
требуется пояснение. что за константа в коде `-1`
P.S. добавь ссылку на задачу в текст PR

2023-01-07 14:17 UTC, iliadmitriev commented on dict/word_occurrence_number.py
> +            print(data[line], end=' ')
для лучшей читаемости кода лучше разделить операцию чтения из словаря и операцию записи в словарь увеличенного на 1 значения.
к стати хорошая идея читать значение из словаря с помощью метода get у словаря.

а что значит константа -1, и почему они именно -1 равна?

2023-01-08 08:15 UTC, Maksonchik88 commented on dict/word_occurrence_number.py
> +            print(data[line], end=' ')
Как разделить?

2023-01-08 08:17 UTC, Maksonchik88 commented on dict/word_occurrence_number.py
> +            print(data[line], end=' ')
-1 в методе потому, что в условии считать с 0 количество слов в словаре, а не с 1.
data[line] = data.get(line, -1)
            data[line] += 1

2023-01-08 08:20 UTC, Maksonchik88 commented on dict/word_occurrence_number.py
> +            print(data[line], end=' ')
и выходит, что если не ключа в словаре, то мы в значении -1 и потом прибавляем к значению 1. Но если ключ есть, то гет возвращает существующее значение и потом мы его переписываем, добавляя единицу к значению

2023-01-08 09:15 UTC, iliadmitriev approved these changes

2023-01-08 09:28 UTC, merged