Контрольная по ударениям
Maksonchik88/Kirienko_lessons_lists pull request #37
Opened 2023-01-12 06:08 UTC by Maksonchik88

https://informatics.msk.ru/mod/statements/view.php?id=4535&chapterid=3768#1 

*Открыл файл
*Инициализировал словарь, где ключ - слово в без ударений, а значение - список слов с обозначенными ударениями *Инициализировал список слов, которые нужно проверить
 *Инициализировал словарь, в котором ключ - проверяемое слово, значение - количество ударений в слове 
*Циклом проверил, сколько ударений с проверяемом слове. Если более одного или ни одного, то это ошибка

*Не разобрался, как проверить слово в значениях первого словаря....
*Не убрал отладочные принты Lol

2023-01-12 06:58 UTC, iliadmitriev commented on dict/accent_test.py
> +            letters_counter += 1
это предложение (не обязательно)
можно вот эти 4 строки заменить на генераторное выражение.
хорошая практика будет.

2023-01-12 07:16 UTC, iliadmitriev requested changes
Надо доделать

2023-01-12 07:16 UTC, iliadmitriev commented on dict/accent_test.py
> +data = {}
более осознанные имена переменным надо дать, 
data это что то абстрактное.

2023-01-12 07:16 UTC, iliadmitriev commented on dict/accent_test.py
> +        mistakes += 1
Хорошая идея проверить сначала, не стоит ли в слове ударение или стоит больше 2-х ударений и считать автоматически это ошибкой.
Но вот нет альтернативного сценария, когда в слове единственное ударение, то нужно по результатам проверки его наличия (или отсутствия) в заранее подготовленном словаре, принимать решение о том является ли это ошибкой или нет.
А то так получается что весь предыдущий код не нужен, иначе зачем ты делал словарик и не используешь его.
Судя по комментам, я так понял задачу просто не дописал.

2023-01-12 16:11 UTC, Maksonchik88 commented on dict/accent_test.py
> +            letters_counter += 1
а как?

2023-01-12 16:36 UTC, Maksonchik88 commented on dict/accent_test.py
> +        mistakes += 1
да, не дописал

2023-01-12 17:55 UTC, iliadmitriev commented on dict/accent_test.py
> +        mistakes += 1
Давай дописывай, пару строк осталось до решения 😉

2023-01-16 16:17 UTC, iliadmitriev requested changes
Задача решена не верно.
Для тестовых данных:
```
4
cAnnot
cannOt
fOund
pAge
thE pagE cAnnot be found
```
Программа должна выдать 3: в 2-х словах `be` `found` ударение не стоит, а в слове `pagE` ударение не верное

Программа выдает ответ 2

2023-01-16 16:17 UTC, iliadmitriev commented on dict/accent_test.py
> +        word] > 1 or data_completed[word] == 0:
Задача решена не верно.

2023-01-17 08:51 UTC, iliadmitriev approved these changes
отличная работа!

2023-01-17 09:37 UTC, merged